# -*- coding: utf-8 -*-
"""mflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gQWboK-BssKyUvSfTUzXi5hvJMG2Ud7a
"""


import pandas as pd
import mlflow
from mlflow.models.signature import infer_signature
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
# Load dataset
data = pd.read_csv('train.csv')  # Replace 'train.csv' with your uploaded file's name
print(data.head())

# Drop rows with missing values
data = data.dropna()

# Encode categorical variables
encoder = LabelEncoder()
for column in ['Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area', 'Loan_Status', 'Dependents']:  # Added 'Dependents' here
    data[column] = encoder.fit_transform(data[column])

# Define features (X) and target (y)
X = data.drop(['Loan_ID', 'Loan_Status'], axis=1)
y = data['Loan_Status']

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



with mlflow.start_run(run_name="Arslan_exp_3"):
    # Train the model
    model = RandomForestClassifier(random_state=42)
    model.fit(X_train, y_train)

    # Evaluate the model
    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)

    # Log model and metrics in MLflow with input example and signature
    input_example = X_test.iloc[:1]  # Single test example
    signature = infer_signature(X_train, model.predict(X_train))
    
    mlflow.sklearn.log_model(model, "loan_model", signature=signature, input_example=input_example)
    mlflow.log_metric("accuracy", accuracy)
    mlflow.log_metric("len_train", len(X_train))

    print(f"Model logged with accuracy: {accuracy}")
    